defaults:
  project: platform
  build: nightly
  golden_build: nightly
  customer: thales
  mail_to: kritika.saxena@guavus.com,Jyoti.Arora@guavus.com,samarth.goel@guavus.com
  headers: True
  delimiter: ","
  aggregate: False
  sort_columns: False
  config_separator: "="
jobs:
  hive_to_hive:
    input:
      input1:
        source: hive
        db_name: randynamic_db_name
        table_name: randynamic_table_name
        where_clause:
        select_statement: '*'
        group_by_clause:
    output:
      output1:
        actual:
          source: hive
          db_name: aut_squad_hive_db
          table_name: aut_squad_hive_table
          where_clause:
          ignore_columns: appnameid,deviceid,searchkeyword,httpreferer,deviceosversion,gds,sessionidtype4,sessionidtype3,sessionidtype2,sessionidtype1,duration,mcc,ci,att_content_type,accountid,deviceos,imei,spt2category,contenttype,tier1_id,contentupbytes,location8,devicemanufacturer,location7,location6,location5,tier2_id,location4,location3,location2,location1,contentdownbytes,att_os,mobileapp,wcsubid,recordendtime,recordendtimedateformat,apn,mnc,timezone,att_application,contenttypeid,mobileappcategory,url,appprotocol,formatedrat,att_device,ipprotocol,destinationip,ntc_id,devicename,lac,httpmethod,adidtimestamp,sourceip,att_domain,uaidagent,adid,ods3,ods2,ods1,devicegroup,responsecode,lineformat,att_sp,spt1category,serviceprovider,destinationport,downpackets,host,roamingcountry,topologylevel2,sourceport,downbytes,topologylevel1,roamingoperator,recordstarttime,recordstarttimedateformat,time
          measures: output_type
  psql_to_psql:
    input:
      input1:
        source: psql
        db_name: &psql_to_psql_input_db aut_squad_pgsql_db
        table_name: &psql_to_psql_input_table aut_squad_pgsql_table
        select_statement: '*'
        where_clause:
        group_by_clause:
    output:
      output1:
        actual:
          source: psql
          db_name: aut_squad_pgsql_db
          table_name: aut_squad_pgsql_table
          where_clause:
          ignore_columns: id
          measures: description,name,url,displayname
  hdfs_to_hdfs_parquet:
    input:
      input1:
        source: hdfs
        base_path: &hdfs_to_hdfs_parquet_input_base_path /tmp/aut_squad_dir/parquet
        file_format: parquet
        delimiter: "\t"
        compression: gz
        headers: False
    output:
      output1:
        actual:
          source: hdfs
          base_path: /tmp/aut_squad_dir/parquet
          aggregation_level: 0
          file_format: parquet
          delimiter: "\t"
          compression: gz
          headers: False
  &hdfs_csv hdfs_to_hdfs_csv:
#    configs:
#      config1:
#        location: local
#        base_path:  "/tmp/aut_squad_dir/automation_squad.yml"
#        file_format: yaml
#        components:
#          - MANAGEMENT
#          - NAMENODE
#        properties:
#          "[2].tasks[0].docker_image.name": "image3"
#    schedule:
#      source: api
#      module:  nimble.actions.sample.sample_actions
#      class:
#        class_name: SampleActions
#        class_parameters:
#          - *hdfs_csv
#      method:
#        method_name: schedule_job_via_api
    input:
      input1:
        source: hdfs
        base_path: /tmp/aut_squad_dir/csv
        file_format: csv
        file_name_flag: False
    output:
      output1:
        actual:
          source: hdfs
          base_path: /tmp/aut_squad_dir/csv
          file_format: csv
          ignore_diff_column_indexes: 1,3
      output2:
        actual:
          source: hdfs
          base_path: /tmp/aut_squad_dir/csv
          file_format: csv
          ignore_diff_column_indexes: 1,3
  local_to_hdfs:
    input:
      input1:
        source: local
        base_path: /tmp/aut_squad_dir/csv
        file_format: csv
        file_name_flag: True
        components:
          - MASTER_NAMENODE
    output:
      output1:
        actual:
          source: hdfs
          base_path: &local_to_hdfs_output_base_path /tmp/aut_squad_dir/csv
          file_format: csv
  fileserver_to_hdfs:
    input:
      input1:
        source: file_server
        base_path: modules/platform/validation/aut_squad_test_data/input_output_sources/fileserver/csv/
        file_format: csv
    output:
      output1:
        actual:
          source: hdfs
          base_path: &fileserver_to_hdfs_output_base_path /tmp/aut_squad_dir/csv
          file_format: csv
  elasticsearch_to_elasticsearch:
    input:
      input1:
        source: elasticsearch
        es_index: randynamic_es_index
    output:
      output1:
        actual:
          source: elasticsearch
          es_index: randynamic_es_index
  hbase_to_hbase:
    input:
      input1:
        source: hbase
        table_name: randynamic_table_name
        scan_filter: FirstKeyOnlyFilter()
    output:
      output1:
        actual:
          source: hbase
          table_name: aut_squad_hbase_table
          scan_filter: FirstKeyOnlyFilter()
  media_plane_microapp1:
    input:
      input1:
        source: hdfs
        base_path: /tmp/partition_date=2019-07-20
        file_format: csv
        file_name_flag: False
        delimiter: ","
    output:
      output1:
        actual:
          source: hive
          db_name: network360_volte
          table_name: media_plane_table_chaos